I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script call
    call neighbor_scene
  File "renpy/common/00start.rpy", line 81, in script
    return
Exception: Could not find return label (u'/Users/dannyortega13/Documents/renpy/TooManyTreesGame/game/neighbor_scene.rpy', 1429833752, 4).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script call
    call neighbor_scene
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "/Users/dannyortega13/Downloads/renpy-6.99.1-sdk/renpy/ast.py", line 1336, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "/Users/dannyortega13/Downloads/renpy-6.99.1-sdk/renpy/execution.py", line 473, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'/Users/dannyortega13/Documents/renpy/TooManyTreesGame/game/neighbor_scene.rpy', 1429833752, 4).

Darwin-14.1.0-x86_64-i386-64bit
Ren'Py 6.99.1.329
test 0.0
