I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main_avatar_images.rpy", line 12, in script
    python:
  File "game/main_avatar_images.rpy", line 13, in <module>
    a_oneal_blink = dir_filenames('a_oneal_blink')
NameError: name 'dir_filenames' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/main_avatar_images.rpy", line 12, in script
    python:
  File "/Users/dannyortega13/Downloads/renpy-6.99.1-sdk/renpy/ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/dannyortega13/Downloads/renpy-6.99.1-sdk/renpy/python.py", line 1432, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/main_avatar_images.rpy", line 13, in <module>
    a_oneal_blink = dir_filenames('a_oneal_blink')
NameError: name 'dir_filenames' is not defined

Darwin-14.1.0-x86_64-i386-64bit
Ren'Py 6.99.1.329
 
